language: ruby
sudo: false
cache: bundler

rvm:
  - 2.0.0
  - 2.1
  - jruby-head

before_install: gem install bundler
install: bundle install
script:
  - bundle exec rake test_with_coveralls

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
