language: ruby
rvm:
  - 2.0.0
  - 2.1
  - jruby-head

before_install: gem install bundler
install: bundle install
script:
  - export VELIBE_TOKEN="junk"
  - bundle exec rake spec

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
