#+TITLE: Velibe
#+AUTHOR: adrien

Ma petite appli pour PlanVelib

* Idees
Application ligne de comamnde pour intérroger api.
- initiallement: juste affiche nb vélo disponible, attaches. non station

- puis calcul si trajet possible. (préenregistré: cehc velo puis attache)
  (nb disponnible, warning)


* Feature incrémentales

** Basic
juste query à l'api
classe request?

** test/erros


** Création Classe Station

* Recherches
** ruby
options lignes de commande ruby
https://github.com/visionmedia/commander
** aPI
http://linuxfr.org/users/16ar/journaux/velib-api-rest-de-jcdecaux-acces-en-go
https://developer.jcdecaux.com/#/opendata/vls?page=dynamic
*** Identification.
Clé d'API
c9ce7179fe009f45d27565e5de702fab6da12dcd
utiliser clé:
GET https://api.jcdecaux.com/vls/v1/stations?contract={contract_name}&apiKey={api_key}

GET https://api.jcdecaux.com/vls/v1/stations?contract=paris&apiKey=c9ce7179fe009f45d27565e5de702fab6da12dcd

contract=paris
*** Format données

donnée station
#+BEGIN_SRC js
  {
      "number": 123,
      "contract" : "Paris",
      "name": "nom station",
      "address": "adresse indicative",
      "position": {
          "lat": 48.862993,
          "lng": 2.344294
      },
      "banking": true,
      "bonus": false,
      "status": "OPEN",
      "bike_stands": 20,
      "available_bike_stands": 15,
      "available_bikes": 5,
      "last_update": <timestamp>
  }
#+END_SRC

#+NAME: Données statiques
- number :: le numéro de la station. Attention, ce n'est pas un id, ce numéro n'est unique qu'au sein d'un contrat
- contract :: le nom du contrat de cette station
- name :: le nom de la station
- address :: adresse indicative de la station, les données étant brutes, parfois il s'agit plus d'un commentaire que d'une adresse.
- position :: les coordonnées au format WGS84
- banking :: indique la présence d'un terminal de paiement
- bonus :: indique s'il s'agit d'une station bonus

#+NAME: Données dynamiques
- status :: indique l'état de la station, peut être CLOSED ou OPEN
- bike _stands :: le nombre de points d'attache opérationnels
- available_bike_stands :: le nombre de points d'attache disponibles pour y ranger un vélo
- available_bikes :: le nombre de vélos disponibles et opérationnels
- last_update :: timestamp indiquant le moment de la dernière mise à jour en millisecondes depuis Epoch
#+NAME: stations particulière
https://api.jcdecaux.com/vls/v1/stations/{station_number}?contract={contract_name} HTTP/1.1

Liste des stations: GET https://api.jcdecaux.com/vls/v1/stations HTTP/1.1
*** station intéressante
| Numéro | addresse                        | lieu                 |
|--------+---------------------------------+----------------------|
|   5020 | 03 RUE DES FOSSES SAINT BERNARD | institut monde arabe |
|   5021 | 41 RUE JUSSIEU                  | jussieu              |
|   5023 | 13 RUE JUSSIEU                  |                      |
|   4005 | 2 QUAI DES CELESTINS            | Sully morlan         |
|  10035 | 1 BOULEVARD DE LA CHAPELLE      | chez moi             |
|  10031 | 48 RUE LOUIS BLANC              | bulle                |
|  19003 | 3 QUAI DE LA SEINE              | mk2 seine            |
|  19004 | 4 QUAI DE LA LOIRE              | mk2 loire            |
